x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

volumes:
  db:

services:
  sopds:
    build:
      context: .
      dockerfile: Dockerfile
    image: lonecrazyvanger/sopds:0.47-devel
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - SOPDS_TMBOT_ENABLE=True
      - SOPDS_SU_EMAIL=${SOPDS_SU_EMAIL}
      - SOPDS_SU_NAME=${SOPDS_SU_NAME}
      - SOPDS_SU_PASS=${SOPDS_SU_PASS}
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - MIGRATE=True
    ports:
      - 8082:8001
    volumes:
      - ${LIBRARY_PATH}:/library:ro
    <<: *logging

  db:
    image: postgres:14.8
    # set shared memory limit when using docker-compose
    shm_size: 1gb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      # - LANG=ru_RU.utf8
      # - POSTGRES_INITDB_ARGS="--locale-provider=icu --icu-locale=ru-RU"
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    <<: *logging

  # adminer:
  #   image: adminer
  #   depends_on:
  #     - db
  #   restart: always
  #   ports:
  #     - 8780:8080